### ISSUE TITLE
CCR1 - Fast API - Academic Databases Directory

### ISSUE THREAD

**Issue by beedawn** [beedawn/scrapescholar#137]
Write tests for these folders and LOC to improve code coverage:
academic_databases/SearchResult.py                     17     15      0      0    12%   7-21
academic_databases/ScienceDirect/sciencedirect.py      19     14      6      0    20%   11-45
academic_databases/Scopus/scopus.py                    33     25      6      0    21%   11-63

100 LOC

**Comment by tristanhamid** [comment]
![Image](https://github.com/user-attachments/assets/2aebc017-7629-4cab-88b6-6c099bbc3d9c)

100% coverage for Searchresult.py

**Comment by tristanhamid** [comment]
![Image](https://github.com/user-attachments/assets/e1e1b753-c841-4f69-8784-b364d46c1e78)

**Comment by tristanhamid** [comment]
![Image](https://github.com/user-attachments/assets/907d992d-3b4f-4427-9f0f-8e737d1a5f9c)

**Comment by tristanhamid** [comment]
This CCR was delayed due to VM issues earlier this week. Spent Monday trying to debug with no solution.

Tuesday Brilzen and I got on a call and configured the VM and found a bug that we still do not have the solution for. It is related to the fact  that my VM will throw an error if I try to run tests with _pytest_. Brilzen and I discovered that I must use _python -m pytest tests/_ in order for the tests to run. 
Here is a link to the recorded discussion we had. It can be used in the future to make notes, although for now the README seems to be okay. The issues I was having seemed to be machine-specific (or user error on my part). 

Wednesday I finally was able to test the code on the VM and get ~90% code coverage for these directories. 

I have a feeling that the first commit will still fail pipeline testing because I had to mute several of the first test functions in test_scopus because it was giving a 404 error. This is a weird issues because these tests were written and passing before I started working on the test files.
