### ISSUE TITLE
AR9 - The system shall utilize containerization for the database to ensure consistent and reliable deployment across different environments.

### ISSUE THREAD

**Issue by beedawn** [beedawn/scrapescholar#51]
Title: AR-9 
Priority: Medium 
Estimation: 5 
Risk: Low
Requirement: AR-9
## User Story  
The system shall utilize containerization for the database to ensure consistent and reliable deployment across different environments.
## Acceptance Criteria  
Given a containerization setup for the database, 
When the database container is built and deployed, 
Then it should work consistently across development, staging, and production environments. 

Given a new environment setup, 
When the database container is deployed, 
Then it should be fully functional with minimal configuration.

### Definition of Done 
- [x] Dockerfile for the database container is created and reviewed. 
- [x] Database containers are built and tested locally. 
- [x] Deployment scripts for different environments (development, staging, production) are created and validated. 
- [ ] Documentation on setup and configuration of the containerized database is provided. 
- [x] Deployment is completed and validated in all target environments.

**Comment by brilzen** [comment]
The following tasks will be completed part of AR-8
Documentation on setup and configuration of the containerized database is provided. 

Deployment is completed and validated in all target environments.

**Comment by beedawn** [comment]
Awaiting Test cases 2 and 3 to be written once the other docker containers are completed.

**Comment by brilzen** [comment]
@beedawn can we close this since all feasible test cases have been completed https://github.com/beedawn/scrapescholar/pull/171
Completed Tests:
UTAR 9.1: Verified database containerization for consistent deployment.
UTAR 9.3: Validated database persistence across container restarts.
UTAR 8.1 & 8.2: Verified FastAPI integration with PostgreSQL.
Deferred Tests:
UTAR 9.2 & 8.3: Require full deployment to a production-like environment.
